language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - sudo apt-get install python-dev libevent-dev
  - pip install Cython

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/py2kreqs.txt; fi 
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements/py3kreqs.txt; fi
  - python setup.py install

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -m unittest discover; fi
