language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

before_install:
  - sudo apt-get install python-dev libevent-dev
  - pip install --use-mirrors Cython

script: python -m unittest discover test
install: python setup.py install