language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

before_install:
  - sudo apt-get install python-dev libevent-dev
  - pip install --use-mirrors Cython

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; pip install --use-mirrors -r requirements/py2kreqs.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --use-mirrors -r requirements/py2kreqs.txt; fi 
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install --use-mirrors -r requirements/py3kreqs.txt; fi
  - python setup.py install

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -m unittest discover; fi